language: java
jdk:
  - openjdk11
script: asdf plugin-test grails https://github.com/weibemoura/asdf-grails.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
